# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: CI

on: ['pull_request']

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - run: echo ref -- ${{github.head_ref}}
      - if: contains(github.head_ref, 'fail')
        run: exit 1
