# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: CI

on: ['push', 'pull_request']

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - if: contains(github.ref, 'fail')
        run: exit 1
