# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: Test Merging PRs

on:
  check_suite:   

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
      - name: npm install
        run: npm install
      - name: merge pr
        run: node ./node_modules/@malleatus/nyx/dist/index.js merge
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_CONTEXT: ${{ toJson(github) }}
